[package]
name = "atomic-slot"
version = "0.1.0"
edition = "2024"

[features]
default = ["std"]
std = []

[dependencies]

[target.'cfg(loom)'.dependencies]
loom = "0.7"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(loom)'] }
